apiVersion: apps/v1
kind: Deployment
metadata:
  name: nachrichten-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nachrichten-backend
  template:
    metadata:
      labels:
        app: nachrichten-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: nachrichten-backend
        image: sgse2021containerregistry.azurecr.io/ms_nachrichten-backend:latest
        ports:
        - containerPort: 8181 
        
--- 
apiVersion: v1
kind: Service
metadata:
  name: nachrichten-backend
spec:
  ports:
  - port: 8181
  selector:
    app: nachrichten-backend
