apiVersion: apps/v1
kind: Deployment
metadata:
  name: nachrichten-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nachrichten-backend
  template:
    metadata:
      labels:
        app: nachrichten-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: nachrichten-backend
        image: sgse2021cr.azurecr.io/ms_nachrichten-backend:latest
        env: 
        - name: DATABASE_DNS
          valueFrom: 
            secretKeyRef: 
              name: messagedb-secret
              key: dns
        - name: DATABASE_USER
          valueFrom: 
            secretKeyRef: 
              name: messagedb-secret
              key: user
        - name: DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: messagedb-secret
              key: password
        - name: DATABASE_ADMIN_PW
          valueFrom: 
            secretKeyRef: 
              name: messagedb-secret
              key: admin_pw
        - name: DATABASE_NAME
          valueFrom: 
            secretKeyRef: 
              name: messagedb-secret
              key: database
        - name: DATABASE_PORT
          valueFrom: 
            secretKeyRef: 
              name: messagedb-secret
              key: port
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef: 
              name: messagedb-secret
              key: url
        - name: RABBIT_MQ
          valueFrom: 
            secretKeyRef: 
              name: rabbitmq-secret
              key: url
        ports:
        - containerPort: 8080
        
--- 
apiVersion: v1
kind: Service
metadata:
  name: nachrichten-backend
spec:
  ports:
  - port: 8080
  selector:
    app: nachrichten-backend
